### ISSUE TITLE
Re-enable codecov once coverage is back up to 90%

### ISSUE THREAD

**Issue by line47** [18F/e-QIP-prototype#1153]
Re-enable codecov

```YML
 - run:	
          name: Code coverage	
          command: make coverage
```

See commit https://github.com/18F/e-QIP-prototype/commit/5a5f30295dcdb6d89ee484da2798432830a59fa1 where coverage was removed
